object Versions {

    const val kotlinVersion = "1.5.10"
    const val appCompatVersion = "1.3.0"
    const val recyclerViewVersion = "1.2.1"
    const val materialVersion = "1.4.0-beta01"
    const val xCoreVersion = "1.5.0"
    const val viewModelVersion = "2.4.0-alpha01"
    const val lifecycleVersion = "2.3.1"
    const val lifecycleRuntimeVersion = "2.4.0-alpha02"
    const val espressoCoreVersion = "3.1.0"
    const val jUnitVersion = "4.12"
    const val coroutinesVersion = "1.5.0"
    const val xFragmentVersion = "1.3.4"
    const val xActivityKtxVersion = "1.2.3"
    const val constraintLayoutVersion = "2.0.4"
    const val retrofitVersion = "2.9.0"
    const val okHttpVersion = "5.0.0-alpha.2"
    const val okHttpLoggingInterceptorVersion = "5.0.0-alpha.2"
    const val daggerHilt = "2.37"
    const val compose = "1.0.0-beta09"
    const val composeActivity = "1.3.0-beta02"
    const val navigationComponent = "2.3.5"
    const val coilVersion = "1.3.2"
}